{{- $data := dict }}
{{- if eq .Values.transfersh.provider "s3" }}
{{- with .Values.transfersh.s3 }}
{{- if and (not .existingSecret) (or .accessKey .secretKey) }}
{{- $_ := set $data "AWS_ACCESS_KEY" .accessKey }}
{{- $_ := set $data "AWS_SECRET_KEY" .secretKey }}
{{- end }}
{{- end }}
{{- end }}
{{- if eq .Values.transfersh.provider "storj" }}
{{- with .Values.transfersh.storj }}
{{- if and (not .existingSecret) .access }}
{{- $_ := set $data "STORJ_ACCESS" .access }}
{{- end }}
{{- end }}
{{- end }}
{{- with .Values.transfersh.httpAuth }}
{{- if and .enabled (not .htpasswd) (not .existingSecret) }}
{{- $_ := set $data "HTTP_AUTH_USER" .user }}
{{- $_ := set $data "HTTP_AUTH_PASS" .pass }}
{{- end }}
{{- end }}
{{- if $data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transfer.sh.fullname" . }}
  labels:
    {{- include "transfer.sh.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
